"""
Pydantic schemas for PR testing automation
Defines data models for PR context, test plans, and test results
"""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime


class PRSummary(BaseModel):
    """Summary for PR list display in UI"""
    pr_id: int
    title: str
    author: str
    status: str
    created_date: str
    source_branch: str
    target_branch: str


class FileChange(BaseModel):
    """Represents a changed file in PR"""
    path: str
    change_type: str  # add, edit, delete, rename
    additions: int = 0
    deletions: int = 0
    diff: Optional[str] = None


class PRContext(BaseModel):
    """Complete PR context for AI processing"""
    pr_id: int
    title: str
    description: Optional[str] = None
    author: str
    reviewers: List[str] = []
    source_branch: str
    target_branch: str
    linked_work_items: List[Dict[str, Any]] = []
    commits: List[Dict[str, Any]] = []
    file_changes: List[FileChange] = []
    impacted_modules: List[str] = []
    impacted_apis: List[str] = []
    impacted_ui_components: List[str] = []
    impacted_database: List[str] = []


class TestInstruction(BaseModel):
    """Single test step for manual or automated execution"""
    step_number: int
    action_type: str  # navigate, click, input, assert, wait, extract
    description: str
    target: Optional[str] = None  # CSS selector or element description
    input_value: Optional[str] = None
    expected_result: str
    test_type: str = "positive"  # positive, negative, edge_case


class TestScenario(BaseModel):
    """Test scenario grouping related test steps"""
    name: str
    description: str
    priority: str = "medium"  # high, medium, low
    test_type: str = "functional"  # functional, integration, regression, smoke


class TestPlan(BaseModel):
    """Complete test plan generated by AI"""
    pr_id: int
    summary: str
    test_scenarios: List[TestScenario] = []
    manual_steps: List[TestInstruction] = []
    automated_steps: List[TestInstruction] = []
    prerequisites: List[str] = []
    test_data_requirements: List[str] = []


class TestStepResult(BaseModel):
    """Result of a single test step execution"""
    step_number: int
    status: str  # PASS, FAIL, ERROR, SKIP
    description: str
    error_message: Optional[str] = None
    screenshot_path: Optional[str] = None
    execution_time: float = 0.0


class TestExecutionResult(BaseModel):
    """Complete test execution results"""
    pr_id: int
    total_tests: int
    passed: int
    failed: int
    errors: int
    skipped: int
    pass_rate: float
    execution_time: float
    step_results: List[TestStepResult] = []
    summary: str = ""
